### ISSUE TITLE
Make gpu code path support adiabatic wall BC

### ISSUE THREAD

**Issue by trevilo** [pecos/tps#139]
At the moment, gpu code path runs but computes nonsense with adiabatic BCs because of the following switch statement in [wallBC.cpp](https://github.com/pecos/tps/blob/7ce3582111cdb85ab88ebf3e61e499d687c6c327/src/wallBC.cpp#L571):

```
 // compute mirror state
 switch (type) {
    case WallType::INV:
        computeInvWallState_gpu_serial(&u1[0], &u2[0], &nor[0], dim, num_equation);
        break;
     case WallType::VISC_ISOTH:
        computeIsothermalState_gpu_serial(&u1[0], &u2[0], &nor[0], wallTemp, gamma, Rg, dim, num_equation, fluid);
        break;
      case WallType::VISC_ADIAB:
        break;
 }
```
This leads to uninitialized `u2` for the adiabatic case.

At a minimum, this should scream if you try to use adiabatic rather than silently continue, but we should really just support it.

**Comment by dreamer2368** [comment]
Adiabatic wall is now supported at least on the cuda path, with PR #147 . hip path remains unsupported.

**Comment by trevilo** [comment]
Closing since PR #147 has been merged.
